ARG BUILD_ARCH
FROM andriiradchenko/web_recognition:${BUILD_ARCH}
VOLUME ["/root/face_recognition/examples"]
VOLUME ["/root/face_recognition/examples/static"]
VOLUME ["/root/face_recognition/examples/data"]
EXPOSE 5001
